global:
  config:
    dry: true
    check: true
    headless: false

  script:
    onError: null
    onCheckError: null
    onSuccess: null

  log:
    log: 1
    logPath: "./logs"
    logPrefix: null
    logSuffix: null
    logDate: false
    logTime: false
    logOverwrite: true
    logNames:
      console: "run"
      checkfile: "check"
      copyfiles: "copy"
      error: "error"
      debug: "debug"